# Generated by Django 5.2.12 on 2026-03-30 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0005_caso_chat_habilitado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Cuestionario Inicial I-130", max_length=200
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Molde de Formulario",
                "verbose_name_plural": "Moldes de Formularios",
            },
        ),
        migrations.CreateModel(
            name="MensajeInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuerpo", models.TextField()),
                (
                    "adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="mensajeria/%Y/%m/"
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_internos",
                        to="crm.caso",
                    ),
                ),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados_internos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_recibidos_internos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje Interno",
                "verbose_name_plural": "Mensajes Internos",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos",
                    models.JSONField(
                        default=dict,
                        help_text="Almacena todas las respuestas del usuario",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("BLOQUEADO", "Bloqueado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_formularios",
                        to="crm.caso",
                    ),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="formularios.formulario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Formulario",
                "verbose_name_plural": "Respuestas de Formularios",
            },
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Datos del Peticionario", max_length=200
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "repetible",
                    models.BooleanField(
                        default=False,
                        help_text="Permite al usuario agregar múltiples instancias de esta sección",
                    ),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secciones",
                        to="formularios.formulario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pregunta", models.CharField(max_length=500)),
                (
                    "ayuda_visual",
                    models.TextField(
                        blank=True, help_text="Pequeña explicación para el usuario"
                    ),
                ),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("TEXTO", "Texto Corto"),
                            ("TEXTAREA", "Texto Largo"),
                            ("FECHA", "Fecha"),
                            ("EMAIL", "Email"),
                            ("NUMERO", "Número"),
                            ("SELECT", "Selección Múltiple"),
                            ("PAIS", "País"),
                            ("ESTADO_US", "Estado USA"),
                            ("DIRECCION_US", "Dirección USA (Completa)"),
                        ],
                        default="TEXTO",
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("es_requerida", models.BooleanField(default=True)),
                (
                    "opciones",
                    models.TextField(
                        blank=True,
                        help_text="Para selección múltiple, separar por comas",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="formularios.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["orden"],
            },
        ),
    ]
