# Generated by Django 5.2.12 on 2026-03-31 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregunta",
            name="formulario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas_sueltas",
                to="formularios.formulario",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="formularios.seccion",
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="tipo_dato",
            field=models.CharField(
                choices=[
                    ("TEXTO", "Texto Corto"),
                    ("TEXTAREA", "Texto Largo"),
                    ("FECHA", "Fecha"),
                    ("EMAIL", "Email"),
                    ("NUMERO", "Número"),
                    ("SELECT", "Selección Múltiple"),
                    ("PAIS", "País"),
                    ("ESTADO_US", "Estado USA"),
                    ("DIRECCION_US", "Dirección USA (Completa)"),
                    ("ARCHIVO", "Archivo / Imagen"),
                ],
                default="TEXTO",
                max_length=20,
            ),
        ),
    ]
