# Generated by Django 5.2.12 on 2026-03-31 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0002_pregunta_formulario_alter_pregunta_seccion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="formulario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas_sueltas",
                to="formularios.formulario",
            ),
        ),
    ]
