# Generated by Django 5.2.12 on 2026-03-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0003_alter_pregunta_formulario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seccion",
            options={"verbose_name_plural": "Secciones"},
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="formulario",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="orden",
        ),
        migrations.AddField(
            model_name="seccion",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="seccion",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="seccion",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="seccion",
            name="repetible",
            field=models.BooleanField(
                default=False,
                help_text="¿Permitir agregar múltiples instancias (ej: empleos)?",
            ),
        ),
        migrations.CreateModel(
            name="FormularioSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formularios.formulario",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formularios.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Secciones",
                "ordering": ["orden"],
                "unique_together": {("formulario", "seccion")},
            },
        ),
    ]
