# Generated by Django 5.2.12 on 2026-04-02 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_userprofile_is_demo"),
        (
            "formularios",
            "0004_alter_seccion_options_remove_seccion_formulario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios_moldes",
                to="crm.agencia",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secciones_moldes",
                to="crm.agencia",
            ),
        ),
    ]
