# Generated by Django 5.2.2 on 2026-04-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0005_formulario_agencia_seccion_agencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulario",
            name="agencia",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="agencia",
        ),
    ]
