# Generated by Django 5.2.2 on 2026-04-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_alter_caso_sub_tipo_alter_caso_tipo"),
        ("formularios", "0006_remove_formulario_agencia_remove_seccion_agencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="agencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios",
                to="crm.agencia",
            ),
        ),
        migrations.AddField(
            model_name="seccion",
            name="agencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secciones_formularios",
                to="crm.agencia",
            ),
        ),
    ]
