# Generated by Django 5.2.12 on 2026-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0007_formulario_agencia_seccion_agencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestaformulario",
            name="edit_habilitado",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el cliente puede seguir editando aunque el estado no sea BORRADOR. El admin controla esto.",
            ),
        ),
        migrations.AddField(
            model_name="respuestaformulario",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Token único para acceso público sin login",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
