# Generated by Django 5.2.12 on 2026-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0008_respuestaformulario_edit_habilitado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="respuestaformulario",
            name="edit_habilitado",
        ),
        migrations.AddField(
            model_name="respuestaformulario",
            name="cerrado",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el formulario está cerrado y el cliente NO puede editar respuestas. Mientras esté en False, el cliente puede editar aunque haya enviado.",
            ),
        ),
    ]
