# Generated by Django 5.2.12 on 2026-03-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Define la posición en el embudo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado del Caso",
                "verbose_name_plural": "Estados de los Casos",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Caso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: Juan Perez - Residencia", max_length=200
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("TURISTA", "Turista"), ("INMIGRANTE", "Inmigrante")],
                        max_length=20,
                    ),
                ),
                (
                    "sub_tipo",
                    models.CharField(
                        choices=[
                            ("AJUSTE", "Ajuste de Estatus"),
                            ("CONSULAR", "Proceso Consular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("ultima_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "beneficiario_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casos_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preparador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casos_gestionados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos",
                        to="crm.casestatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActualizacionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actualizaciones",
                        to="crm.caso",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("detalle", models.TextField(blank=True)),
                (
                    "fecha_programada",
                    models.DateField(
                        blank=True, help_text="Cuándo planeas hacerlo", null=True
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, help_text="Fecha límite legal", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("prioridad_alta", models.BooleanField(default=False)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="crm.caso",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_vencimiento", "fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="Credencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_sitio",
                    models.CharField(
                        help_text="Ej: Portal CEAC / USCIS", max_length=100
                    ),
                ),
                ("usuario", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credenciales",
                        to="crm.caso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Derivado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivados",
                        to="crm.caso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="expedientes/%Y/%m/")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("CLIENTE", "Subido por Cliente"),
                            ("PREPARADOR", "Subido por Preparador"),
                            ("ENTREVISTA", "Llevar a Entrevista"),
                            ("OTROS", "Descargables/Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre_documento", models.CharField(max_length=255)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="crm.caso",
                    ),
                ),
            ],
        ),
    ]
