# Generated by Django 5.2.12 on 2026-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="detalle",
            field=models.TextField(
                blank=True, help_text="Mensaje o detalle del documento", null=True
            ),
        ),
    ]
