# Generated by Django 5.2.12 on 2026-03-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_documento_user_can_view_mensajecliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionMensajes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limite",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Número máximo de mensajes permitidos por período",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Por Día"),
                            ("SEMANAL", "Por Semana"),
                            ("MENSUAL", "Por Mes"),
                        ],
                        default="DIARIO",
                        help_text="Ventana de tiempo en que aplica el límite",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Mensajes",
                "verbose_name_plural": "Configuración de Mensajes",
            },
        ),
    ]
