# Generated by Django 5.2.12 on 2026-03-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_configuracionmensajes"),
    ]

    operations = [
        migrations.AddField(
            model_name="caso",
            name="chat_habilitado",
            field=models.BooleanField(
                default=True,
                help_text="Permite al cliente enviar mensajes al preparador desde su portal",
            ),
        ),
    ]
