# Generated by Django 5.2.12 on 2026-03-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_caso_chat_habilitado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_proximos_vencer",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Días de antelación para mostrar tareas en 'Próximas a Vencer'",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Dashboard",
                "verbose_name_plural": "Configuración del Dashboard",
            },
        ),
        migrations.AddField(
            model_name="casestatus",
            name="color",
            field=models.CharField(
                default="#0d6efd",
                help_text="Color en formato HEX para las etiquetas",
                max_length=7,
            ),
        ),
    ]
