# Generated by Django 5.2.12 on 2026-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_configuraciondashboard_casestatus_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credencial",
            options={"verbose_name_plural": "Credenciales"},
        ),
        migrations.RenameField(
            model_name="credencial",
            old_name="titulo_sitio",
            new_name="sitio_web",
        ),
        migrations.AlterField(
            model_name="credencial",
            name="password",
            field=models.CharField(
                help_text="Almacenado de forma cifrada", max_length=500
            ),
        ),
    ]
