# Generated by Django 5.2.12 on 2026-03-31 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_alter_credencial_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único en la URL (ej: mi-agencia)",
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agencias/logos/"
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Agencias",
            },
        ),
        migrations.AddField(
            model_name="casestatus",
            name="agencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estados_casos",
                to="crm.agencia",
            ),
        ),
        migrations.AddField(
            model_name="caso",
            name="agencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="casos",
                to="crm.agencia",
            ),
        ),
        migrations.AddField(
            model_name="configuraciondashboard",
            name="agencia",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_dashboard",
                to="crm.agencia",
            ),
        ),
        migrations.AddField(
            model_name="configuracionmensajes",
            name="agencia",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_mensajes",
                to="crm.agencia",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_admin_agencia",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, puede editar configuraciones de la agencia.",
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="crm.agencia",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
