# Generated by Django 5.2.12 on 2026-04-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_agencia_casestatus_agencia_caso_agencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(blank=True, max_length=255)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("is_live", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración de Stripe",
                "verbose_name_plural": "Configuración de Stripe",
            },
        ),
        migrations.AddField(
            model_name="agencia",
            name="limite_casos_custom",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sobrescribe el límite del plan si se especifica",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="limite_usuarios_custom",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sobrescribe el límite del plan si se especifica",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="plan",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter"),
                    ("GROWTH", "Growth"),
                    ("PRO", "Pro"),
                    ("SCALE", "Scale"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="STARTER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agencia",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="caso",
            name="esta_archivado",
            field=models.BooleanField(
                default=False,
                help_text="Los casos archivados no cuentan para el límite del plan, pero no se pueden editar ni reabrir.",
            ),
        ),
    ]
