# Generated by Django 5.2.12 on 2026-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_stripeconfig_agencia_limite_casos_custom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tipo",
            field=models.CharField(
                choices=[("MIEMBRO", "Miembro del Equipo"), ("CLIENTE", "Cliente")],
                default="MIEMBRO",
                max_length=15,
            ),
        ),
    ]
