# Generated by Django 5.2.12 on 2026-04-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_userprofile_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
