# Generated by Django 5.2.2 on 2026-04-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_casochecklist_checklisttemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklisttemplate",
            name="agencia",
        ),
        migrations.CreateModel(
            name="CaseChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_asignado", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists_asignados",
                        to="crm.caso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Asignado",
                "verbose_name_plural": "Checklists Asignados",
            },
        ),
        migrations.CreateModel(
            name="CaseChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("completado", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "case_checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.casechecklist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Checklist Asignado",
                "verbose_name_plural": "Ítems de Checklists Asignados",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="crm.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Checklist",
                "verbose_name_plural": "Plantillas de Checklists",
            },
        ),
        migrations.AddField(
            model_name="casechecklist",
            name="checklist_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.checklist",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.checklist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Plantilla",
                "verbose_name_plural": "Ítems de Plantilla",
                "ordering": ["orden"],
            },
        ),
        migrations.DeleteModel(
            name="CasoChecklist",
        ),
        migrations.DeleteModel(
            name="ChecklistTemplate",
        ),
    ]
