# Generated by Django 5.2.2 on 2026-04-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_remove_checklisttemplate_agencia_casechecklist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_casos",
                        to="crm.agencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTipoCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo_caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtipos",
                        to="crm.tipocaso",
                    ),
                ),
            ],
        ),
    ]
