# Generated by Django 5.2.2 on 2026-04-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_tipocaso_subtipocaso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caso",
            name="sub_tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="casos",
                to="crm.subtipocaso",
            ),
        ),
        migrations.AlterField(
            model_name="caso",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="casos",
                to="crm.tipocaso",
            ),
        ),
    ]
