# Generated by Django 5.2.12 on 2026-04-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_alter_caso_sub_tipo_alter_caso_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caso",
            name="sub_tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="caso",
            name="tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
