# Generated by Django 5.2.2 on 2026-04-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_alter_caso_sub_tipo_alter_caso_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caso",
            name="sub_tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.subtipocaso",
            ),
        ),
        migrations.AlterField(
            model_name="caso",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.tipocaso",
            ),
        ),
    ]
