# Generated by Django 5.2.12 on 2026-04-06 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_alter_caso_sub_tipo_alter_caso_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="categoria",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="CategoriaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_documentos",
                        to="crm.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Documento",
                "verbose_name_plural": "Categorías de Documentos",
            },
        ),
    ]
