# Generated by Django 5.2.12 on 2026-04-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_alter_documento_categoria_categoriadocumento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="crm.categoriadocumento",
            ),
        ),
    ]
