# Generated by Django 5.2.12 on 2026-04-15 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_alter_documento_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="caso",
            name="caso_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_casos",
                to="crm.caso",
            ),
        ),
        migrations.AddField(
            model_name="caso",
            name="derivado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caso_especifico",
                to="crm.derivado",
            ),
        ),
    ]
