# Generated by Django 5.2.12 on 2026-04-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_caso_caso_principal_caso_derivado"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="llevar_a_entrevista",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el cliente debe imprimir y llevar este documento a la entrevista.",
            ),
        ),
    ]
