# Generated by Django 5.2.12 on 2026-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_documento_llevar_a_entrevista"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="solicita_eliminacion",
            field=models.BooleanField(
                default=False,
                help_text="Si el cliente ha solicitado eliminar su cuenta y datos por completo.",
            ),
        ),
    ]
