# Generated by Django 5.2.12 on 2026-04-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0022_userprofile_solicita_eliminacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="caso",
            name="instrucciones_especiales",
            field=models.TextField(
                blank=True,
                help_text="Instrucciones paso a paso para el cliente",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PlantillaInstruccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo de la plantilla", max_length=100
                    ),
                ),
                (
                    "contenido",
                    models.TextField(help_text="Contenido de las instrucciones"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_instrucciones",
                        to="crm.agencia",
                    ),
                ),
            ],
        ),
    ]
