# Generated by Django 5.2.12 on 2026-04-24 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0023_caso_instrucciones_especiales_plantillainstruccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstruccionCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrucciones_lista",
                        to="crm.caso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrucción de Caso",
                "verbose_name_plural": "Instrucciones de Casos",
                "ordering": ["orden", "fecha_creacion"],
            },
        ),
    ]
